class WaypointMissionHeadingMode:
    AUTO = 'AUTO'
    USING_INITIAL_DIRECTION = 'USING_INITIAL_DIRECTION'
    CONTROL_BY_REMOTE_CONTROLLER = 'CONTROL_BY_REMOTE_CONTROLLER'
    USING_WAYPOINT_HEADING = 'USING_WAYPOINT_HEADING'
    TOWARD_POINT_OF_INTEREST = 'TOWARD_POINT_OF_INTEREST'
